"""init

Revision ID: 52eb710cb897
Revises: 
Create Date: 2026-04-04 23:25:25.778904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52eb710cb897'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_api_keys_key_hash'), 'employer_api_keys', ['key_hash'], unique=True)
    op.create_table('universities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ogrn', sa.String(length=13), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('accreditation_number', sa.String(), nullable=False),
    sa.Column('api_secret_hash', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='universityapprovalstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'university_staff', 'student', name='userrole'), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=True),
    sa.Column('yandex_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yandex_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('diplomas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('graduate_full_name', sa.Text(), nullable=False),
    sa.Column('graduate_birth_date', sa.Date(), nullable=False),
    sa.Column('specialty_code', sa.String(), nullable=False),
    sa.Column('specialty_name', sa.Text(), nullable=False),
    sa.Column('qualification', sa.Enum('bachelor', 'master', 'specialist', 'phd', name='qualificationtype'), nullable=False),
    sa.Column('study_form', sa.Enum('full_time', 'part_time', 'distance', name='studyform'), nullable=False),
    sa.Column('study_start_year', sa.Integer(), nullable=False),
    sa.Column('study_end_year', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('transcript_hash', sa.String(length=64), nullable=False),
    sa.Column('certificate_token', sa.Uuid(), nullable=False),
    sa.Column('issuer_signature', sa.String(length=512), nullable=True),
    sa.Column('student_user_id', sa.Uuid(), nullable=True),
    sa.Column('employer_link_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'suspended', name='diplomastatus'), nullable=False),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_token')
    )
    op.create_index(op.f('ix_diplomas_graduate_full_name'), 'diplomas', ['graduate_full_name'], unique=False)
    op.create_index(op.f('ix_diplomas_registration_number'), 'diplomas', ['registration_number'], unique=False)
    op.create_index(op.f('ix_diplomas_student_user_id'), 'diplomas', ['student_user_id'], unique=False)
    op.create_table('transcript_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diploma_id', sa.Uuid(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diploma_id', sa.Uuid(), nullable=False),
    sa.Column('verifier_type', sa.String(), nullable=False),
    sa.Column('verifier_ip', sa.String(), nullable=False),
    sa.Column('verifier_org_name', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_logs')
    op.drop_table('transcript_subjects')
    op.drop_index(op.f('ix_diplomas_student_user_id'), table_name='diplomas')
    op.drop_index(op.f('ix_diplomas_registration_number'), table_name='diplomas')
    op.drop_index(op.f('ix_diplomas_graduate_full_name'), table_name='diplomas')
    op.drop_table('diplomas')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('universities')
    op.drop_index(op.f('ix_employer_api_keys_key_hash'), table_name='employer_api_keys')
    op.drop_table('employer_api_keys')
    # ### end Alembic commands ###
